version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  max-same-issues: 50

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment

    misspell:
      locale: US

  exclusions:
    presets:
      - common-false-positives
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
          - unparam

      # Exclude shadow checking on err
      - linters:
          - govet
        text: 'shadow: declaration of "err"'

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/aluedeke/go-codesign
