# GoReleaser configuration for go-codesign
# Documentation: https://goreleaser.com
version: 2

project_name: go-codesign

before:
  hooks:
    - go mod tidy

builds:
  - id: go-codesign
    main: .
    binary: go-codesign
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: aluedeke
    name: go-codesign
  draft: false
  prerelease: auto
